test:
  secret_token: <%= ENV["SECRET_TOKEN_DEV"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

development:
  secret_token: <%= ENV["SECRET_TOKEN_DEV"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

production:
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
